---
version: '2.0'
services:
  nearnode:
    image: glacierluo/near_node:0.5
    expose:
      - port: 3030
        to:
          - global: true
      - port: 24567
        to:
          - global: true
    env:
      # Node data file for rapid deployment.
      - BACKUP_URL=https://near-protocol-public.s3-accelerate.amazonaws.com/backups/mainnet/rpc/data.tar
      # The type of network you want to deploy.
      - NET=mainnet
      # Your near account.
      - ACCOUNT=
      # The S3 key for backup.
      - S3_KEY=
      # The S3 secret for backup.
      - S3_SECRET=
      # The S3 host for backup.
      - S3_HOST=https://s3.filebase.com
      # The storage location of the file in S3,it can be the bucket name directly.
      - KEY_PATH=

profiles:
  compute:
    nearnode:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 500Gi
  placement:
    dcloud:
      pricing:
        nearnode:
          denom: uakt
          amount: 100000

deployment:
  nearnode:
    dcloud:
      profile: nearnode
      count: 1
